add blurb about translating the dev wiki
QuiltMC/developer-wiki pull request #117
Opened 2024-09-28 01:19 UTC by woodiertexas

2024-10-08 16:44 UTC, ix0rai requested changes

2024-10-08 16:44 UTC, ix0rai commented on wiki/landing-page/en.md
> +If you are looking to translate the wiki to your native language, open a translation PR on the [wiki's GitHUb repo](https://github.com/QuiltMC/developer-wiki/compare).
```suggestion
If you are looking to translate the wiki to another language, open a translation PR on the [wiki's GitHub repo](https://github.com/QuiltMC/developer-wiki/). There isn't yet documentation on translating, but you can reference pages such as [the getting started page](https://github.com/QuiltMC/developer-wiki/tree/main/wiki/introduction/getting-started) that are already translated to multiple languages.
```

2024-10-15 22:39 UTC, ix0rai reviewed
i preferred before https://github.com/QuiltMC/developer-wiki/pull/117/commits/85f3c2717cd6da9a1329dd824a94c0132b96034b, i intend on documenting it

2024-10-18 05:26 UTC, woodiertexas commented
> i preferred before [85f3c27](https://github.com/QuiltMC/developer-wiki/commit/85f3c2717cd6da9a1329dd824a94c0132b96034b), i intend on documenting it

"isn't yet documentation..." didn't flow smoothly to me whereas "is currently no documentation..." does flow smoothly to me

2024-10-19 02:43 UTC, ix0rai commented
sure, not going to bikeshed

2024-10-19 02:43 UTC, merged