Displays a 404 error page when trying to access an inexistent wiki page
QuiltMC/developer-wiki pull request #65
Opened 2023-11-02 17:17 UTC by c-leri

2023-11-02 17:34 UTC, OroArmor approved these changes

2023-11-02 17:47 UTC, ix0rai reviewed
does this trigger on pages that aren't linked anywhere? if so, I think the "planned" wording shouldn't be used

2023-11-02 17:51 UTC, c-leri commented
The page that displays for "planned" pages was already there before. I only added a 404 page for routes that don't correspond to a markdown file in the wiki folder

2023-11-03 04:00 UTC, c-leri commented
Ah oops sorry I shouldn't have pushed that to the same branch, that kinda completely changes the purpose of the pull request

2023-11-03 04:09 UTC, c-leri commented
So anyways, this is a proposal of a base for localization as request in issue #18

This changes the structure of the wiki folder to:

```
wiki
└── [category_slug]
    ├── +category.yml
    └── [page_slug]
        ├── +page.yml
        ├── en.md
        └── [lang].md
```

With the pages' metadata taken out of the markdown files and into yaml files.

The markdown files now only include the content of the page so that it can be translated easily by adding a new markdown file for new languages.

For the rest of the text of the application, I simply call a translation store provided by [sveltekit-i18n](https://github.com/sveltekit-i18n)

2023-11-04 02:31 UTC, c-leri commented
I added the french translation as a fonctionnal example

2023-11-04 02:34 UTC, OroArmor commented
Holy shit this is amazing! Thank you so much!

2023-11-04 13:02 UTC, c-leri commented
Glad you like it !

2023-11-14 22:25 UTC, OroArmor commented
Looks like there is still a bit of missing text here (the language selector):
![image](https://github.com/QuiltMC/developer-wiki/assets/13246889/b0be0eea-3b1c-4e66-8306-19ee3503a914)

2023-11-15 00:04 UTC, c-leri commented
The missing text is supposed to be an icon so maybe it isn't loading for some reason

2023-11-15 00:05 UTC, c-leri commented
Also it should be possible to change the locale depending on the route instead of a local storage variable if you'd prefer that

2023-11-15 00:06 UTC, c-leri commented
> The missing text is supposed to be an icon so maybe it isn't loading for some reason

It seems none of the icons are loading actually

2023-11-15 06:35 UTC, c-leri commented
I add to make some tweaks to force sveltekit to generate the wiki pages for all languages.

For example, locales now need to me added to the `prerender.entries` key in the svelte config.
And I also had to add hidden links to the wiki pages in all languages in the sidebar for sveltekit to generate them.

Aside from those two work-around, everything seems to work very nicely :)

2023-11-15 15:33 UTC, c-leri commented
I corrected the issues I found with the previous version such as the page content not reloading correctly when changing locale and it should now work as intended

2023-11-15 20:15 UTC, c-leri commented on src/lib/NavbarLangDropdown.svelte
> +			</span>
Just so that we don't have to add new entries manually when adding locales but this should be statically generated at build time by sveltekit anyway

2023-11-15 22:18 UTC, c-leri commented on src/lib/NavbarLangDropdown.svelte
> +			</span>
Yes I thought about that after reading your comments, I'm currently working on it

2023-11-15 22:52 UTC, c-leri commented
It is now possible to change the locale with javascript disabled! :)

2023-11-24 07:12 UTC, c-leri commented
So I found a solution to the icons not working without javascript by using [unocss icons preset](https://unocss.dev/presets/icons). This is a pure css solution meaning that no javascript is required after build and it relies on [iconify](https://iconify.design/)'s [icon collection](https://icones.js.org/) which includes font awesome icons so the site looks exactly the same as before.

2023-12-14 23:58 UTC, OroArmor commented
Looks great! Sorry for not getting to this sooner, last two weeks of school were very busy. Ill merge this in one week to make sure that others have a chance to look at it.

2023-12-15 00:32 UTC, FirstMegaGame4 commented
I'll verify the translations tomorrow if you want, as I am a french native speaker

2023-12-15 15:32 UTC, c-leri commented on wiki/introduction/setting-up/fr.md
> +Ce fichier définie les métadonnées de votre mod, comme son nom, saon auteurice, sa description, son site web,
"auteurice" est globalement reconnu comme le terme neutre à utiliser à la place de auteur/autrice dans le milieu de l'écriture inclusive. Je me suis dis que comme Quilt était "the loader that cares" ça serait mieux d'utiliser un langage inclusif

2023-12-15 15:59 UTC, c-leri commented on wiki/items/armor/fr.md
> +Les bottes, le casque et le plastron utilise la texture `layer_1` (et ont beaucoup plus de distance entre eux et le skin di joueureuse)
Comme pour "auteurice", "joueureuse" est utilisé comme équivalent neutre pour joueur/joueuse, j'ai tout de même remplacé "di" par "de lae" qui semble plus commun

2023-12-15 16:09 UTC, c-leri commented
Sorry for all the french mistakes! I'm a native speaker to but I was mostly focused on the technical aspect and wasn't careful enough when translating :sweat_smile:
Thank you @FirstMegaGame4 for the review!

2023-12-15 16:14 UTC, FirstMegaGame4 commented
You made a replacement mistake, you replaced "IDEA" by "identifiantIDEA" in some files.
Your work is really great, I'll just check it a last time in about like two hours.

2023-12-15 16:14 UTC, c-leri commented on wiki/introduction/setting-up/fr.md
> +Ce fichier définie les métadonnées de votre mod, comme son nom, saon auteurice, sa description, son site web,
Je pense que c'est surtout une question d'opinion personnelle et du coup je pense pas que l'on puisse prendre cette décision à nous deux

2023-12-15 16:20 UTC, FirstMegaGame4 commented on wiki/introduction/setting-up/fr.md
> +Ce fichier définie les métadonnées de votre mod, comme son nom, saon auteurice, sa description, son site web,
Alors tu devrais au moins l'écrire de façon classique car la ça retire la beauté de la langue française (joueur.reuse) par exemple

2023-12-15 21:50 UTC, FirstMegaGame4 commented on wiki/introduction/setting-up/fr.md
> +Ce fichier définie les métadonnées de votre mod, comme son nom, saon auteur·ice, sa description, son site web,
"son" instead of "saon", "le mod" is masculine

2023-12-15 21:50 UTC, FirstMegaGame4 requested changes

2023-12-15 21:50 UTC, FirstMegaGame4 commented on wiki/introduction/setting-up/fr.md
> +Ce fichier définie les métadonnées de votre mod, comme son nom, saon auteur·ice, sa description, son site web,
"son" instead of "saon", "le mod" is masculine

2023-12-15 22:02 UTC, FirstMegaGame4 approved these changes
If there are remaining french mistakes that we messed up, we will probably fix them in other PRs for other wiki page translations. This PR looks good to me currently.

2023-12-22 16:14 UTC, merged